### ISSUE TITLE
Failed to replicated the sample output

### ISSUE THREAD

**Issue by shukkkur** [avivcaspi/TennisProject#1]
I tried to run your code on my videos but everything I have is output video which detected only one of the players.
It would be very helpful if you upgrade your README.md with instructions of how to run the code.

No doubt your project is amazing, and it is a waste if it can't be used

**Comment by avivcaspi** [comment]
Hello, 
My project is meant to run mainly on official match videos, with camera angle as presented in the Readme file.
Did you use the same kind of videos when you ran the code ?
If not than most of the capabilities of the code won't work well.
As for your suggestion I will update the Readme file to be more specific regarding the options of the projects.
Thank you for commenting.

**Comment by shukkkur** [comment]
I was genuinely interested in the part of your code related to detecting the court lines, can you help me out here, and tell which functions I only need for that purpose?

**Comment by avivcaspi** [comment]
Of course, 
First of all you can see the first detection of the court in the file process.py line 429, and the tracking in line 434.
All the court related code is in court_detection.py and court_reference.py.
Main functions in those files are detect() and track_court().
For full explanation on how the algorithm work you can check this THESE https://spiral.imperial.ac.uk/handle/10044/1/67949
that I mainly used as a basis for the algorithms I implemented.
For summery, for detecting the court, I first detect the lines in the frame using Hough transform, then filter and classify the lines, then I find an homograph matrix that connects the intersection points of the lines I have found to known points on a reference court (this matrix can later on tell me exactly where each line of the court is, even if it is not visible in the frame).
For tracking I used more simple algorithm that is using the previous location and detect the small transition of the court from previous frame.
I hope this is enough for you to understand what is going on, just follow the code and tell me if there is anything you do not understand. 
Just to clarify, I used some heuristics that fits for the angle and videos I used (official video with top camera), so if you wish to use the code for other angles of camera directions, you might need to change some assumptions I used.
